instance/routes.py
from flask import Blueprint, render_template, redirect, url_for, flash, request
from .forms import LoginForm, RegistrationForm
from .models import User
from . import db, bcrypt
from flask_login import login_user, login_required, logout_user, current_user
import pickle
import numpy as np
import pandas as pd
import sklearn
import os
from datetime import datetime
import pickle
from sklearn.preprocessing import StandardScaler
import joblib




main = Blueprint('main', __name__)

# Get the directory where this script resides
basedir = os.path.abspath(os.path.dirname(__file__))

# Load the model
model = joblib.load( os.path.join(basedir, 'random_forest_model.pkl'))
# Load the scaler
scaler = joblib.load(os.path.join(basedir, 'scaler.pkl'))
# minmaxscaler_path = os.path.join(basedir, 'minmaxscaler.pkl')

def get_greeting():
    current_time = datetime.now().time()
    if current_time < datetime.strptime('12:00:00', '%H:%M:%S').time():
        return "Good Morning"
    elif current_time < datetime.strptime('18:00:00', '%H:%M:%S').time():
        return "Good Afternoon"
    else:
        return "Good Evening"


@main.route('/')
def home():
    return render_template('home.html')
@main.route('/crop-detail')
def cropDetail():
    return render_template('crop-detail.html')

@main.route('/login', methods=['GET', 'POST'])
def login():
    form = LoginForm()
    error = None
    if request.method == 'POST':
        user = User.query.filter_by(username=form.username.data).first()
        if user is None or not bcrypt.check_password_hash(user.password_hash, form.password.data):
            error = 'Invalid credentials'
            form.username.data = ''
            form.password.data = ''
            flash('Invalid credentials','error')
        else:
            login_user(user)
            return redirect(url_for('main.dashboard'))
    return render_template('login.html', form=form, error=error)



@main.route('/dashboard', methods=['GET', 'POST'])
@login_required
def dashboard():
    greeting = get_greeting()
    return render_template('dashboard.html', first_name=current_user.first_name, greeting=greeting,form_data=request.form)


@main.route("/predict", methods=['POST'])
def predict():
        N = request.form['Nitrogen']
        P = request.form['Phosporus']
        K = request.form['Potassium']
        temp = request.form['Temperature']
        humidity = request.form['Humidity']
        ph = request.form['Ph']
        rainfall = request.form['Rainfall']

        # Scale the input data
        input_data = scaler.transform([[N,P , K, humidity, rainfall, ph, temp]])
        prediction = model.predict(input_data)
        # single_pred = np.array(feature_list).reshape(1, -1)

        if prediction[0]:
            result = prediction[0]
        else:
            result = "Sorry, we could not determine the best crop to be cultivated with the provided data."
            
        greeting =get_greeting()    
        return render_template('dashboard.html',result = result, first_name=current_user.first_name, greeting=greeting, form_data=request.form)


@main.route('/logout', methods=['GET', 'POST'])
@login_required
def logout():
    logout_user()
    return redirect(url_for('main.login'))


@main.route('/register', methods=['GET', 'POST'])
def register():
    form = RegistrationForm()
    if form.validate_on_submit():
        # Check if email already exists
        user = User.query.filter_by(email=form.email.data).first()
        if user:
            flash('Email already registered. Please choose a different one or log in.', 'danger')
            return redirect(url_for('main.register'))
        
        # If email doesn't exist, proceed with registration
        hashed_password = bcrypt.generate_password_hash(
            form.password.data).decode('utf-8')
        new_user = User(
            first_name=form.first_name.data,
            last_name=form.last_name.data,
            username=form.username.data,
            email=form.email.data,
            password_hash=hashed_password
        )
        db.session.add(new_user)
        db.session.commit()
        
        flash('Registration successful!', 'success')
        return redirect(url_for('main.login'))
    
    return render_template('register.html', form=form)


@main.route('/crops', methods=['GET','POST'])
def crops():
    greeting = get_greeting()
    return render_template('crops.html', first_name=current_user.first_name, greeting=greeting)

@main.route('/about', methods=['GET','POST'])
def about():
    greeting = get_greeting()
    return render_template('about.html', first_name=current_user.first_name, greeting=greeting)

instance/templates/about.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link
  rel="stylesheet"
  href="{{ url_for('static', filename='dash.css') }}"
/>
<link
  href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css"
  rel="stylesheet"
  integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ"
  crossorigin="anonymous"
/>
  <title>Document</title>
<style>
  body {
    margin: 0;
    padding: 0;
    height: 100%;
    width: 100%;
    background-image: url("{{ url_for('static', filename='home2.jpg') }}");
    background-size: cover;
    background-attachment: fixed;
    background-position: center;
}
</style>

</head>
<body>
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
    <div class="container-fluid">
      <span class="navbar-text"> {{greeting}}, {{ first_name }} </span>
      <button
        class="navbar-toggler"
        type="button"
        data-bs-toggle="collapse"
        data-bs-target="#navbarSupportedContent"
        aria-controls="navbarSupportedContent"
        aria-expanded="false"
        aria-label="Toggle navigation"
      >
        <span class="navbar-toggler-icon"></span>
      </button>
      <div
      class="collapse navbar-collapse justify-content-end"
      id="navbarSupportedContent"
    >
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link" href="{{ url_for('main.crops') }}"
            >About Crops</a
          >
        </li>
      </ul>
    </div>
      <div
      class="collapse navbar-collapse justify-content-end"
      id="navbarSupportedContent"
    >
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link" href="{{ url_for('main.logout') }}"
            >About Us</a
          >
        </li>
      </ul>
    </div>
      <div
        class="collapse navbar-collapse justify-content-end"
        id="navbarSupportedContent"
      >
        <ul class="navbar-nav">
          <li class="nav-item">
            <a class="nav-link" href="{{ url_for('main.logout') }}"
              >Logout</a
            >
          </li>
        </ul>
      </div>
    </div>
  </nav>   
















</body>
</html>

instance/templates/home.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <title>Home</title>
    <meta name="description" content="" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link
      rel="stylesheet"
      href="{{ url_for('static', filename='style.css') }}"
    />
    <link href="https://fonts.googleapis.com/css2?family=Karla:ital,wght@0,200..800;1,200..800&family=Manrope:wght@200..800&family=Poppins:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900&display=swap" rel="stylesheet">
    <style>
      body {
        margin: 0;
        padding: 0;
        background-image: url("{{url_for('static', filename='home2.jpg')}}");
        background-size: cover;
        background-position: center;
        background-repeat: no-repeat;
        font-family: "Manrope",sans-serif;
      }
      header {
        background-color: none;
        color: white;
        display: flex;
        flex-direction: column;
        place-items: center;
        height: 90vh;
        place-content: center;
        background-image: linear-gradient(180deg,rgba(0, 0, 0, 0.1) 10%,rgba(0, 0, 0, 0.7) 100%);
      }
      h1{
        font-size: 3.2rem;
      }
      .greeting{
        display: grid;
        gap: 30px;
        justify-items: center;
        text-align: center;
      }
      .greeting span{
        font-size: 1.2rem;
      }
      .link-container{
        height: 10vh;
        background-color: white;
        display: flex;
        place-items: center;
        place-content: space-between;
      }  
      .link-container img{
        width: 60px;
        height: 60px;
      }
      .link-container a{
        background-color: #008457;
        text-decoration: none;
      }
    </style>
  </head>
  <body>
    <header>
      <div class="greeting">
        <h1>Welcome to CropAdvisor</h1>
        <div >
          <span style="color: whitesmoke;">Discover personalized crop recommendations tailored to region's climate and soil conditions,<br> dynamically updating as
          you explore.
          </span>
        </div>
      </div>
    </header>
    <div class="link-container">
      <div style="display: flex; place-items: center; gap: 15px; font-size: 1.3rem; font-weight: bold; margin-left: 150px;">
        <img src="../static/images/plant-svgrepo-com.svg" alt="logo">
        Crop Advisor
      </div>
      <a style="padding: 10px 20px; border-radius: 5px; margin-right: 150px;" href="{{url_for('main.login')}}" >Get started</a>
    </div>
  </body>
</html>

instance/templates/login.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Login</title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width,height=device-height,initial-scale=1">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Raleway:ital,wght@0,100..900;1,100..900&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Karla:ital,wght@0,200..800;1,200..800&family=Manrope:wght@200..800&family=Poppins:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900&display=swap" rel="stylesheet">
</head>
<style>
    body {
        height: 100vh;
        margin: 0;
        height: 100%;
        width: 100vw;
        overflow-x: hidden;
        font-size: 1.5em;
        background-color: whitesmoke;
        font-family: "Raleway", sans-serif;
    }
    .login-section {
        display: flex;
        place-items: center;
        height: 100vh;
    }
    .login-section>* {
        width: 50%;
    }
    #submit:hover {
        border-color: #646cff;
    }
    a {
        font-weight: 500;
        text-decoration: inherit;
    }
    .login-div {
        display: grid;
        justify-content: center;
    }
    .login-div>div {
        padding: 40px 35px;
        display: grid;
        gap: 35px;
        border-radius: 8px;
        background-color: whitesmoke;
        animation: framer-appear 1s ease-in-out;
    }
    .login-div form {
        display: grid;
        gap: 10px;
    }
    .login-div div>p {
        font-size: 1.35rem;
        font-weight: bold;
        text-align: center;
        margin: 0 0 20px 0;
        color: #151C24;
        font-family: "Manrope", sans-serif;
    }
    input {
        border: 2px solid #DEE2E5;
        background-color: transparent;
        font-family: inherit;
        height: 40px;
        outline: none;
        border-radius: 7px;
        padding-left: 10px;
        padding-right: 10px;
        caret-color: forestgreen;
    }
    input:focus {
        border-color: #B35042;
    }
    .login-div #submit {
        width: 350px;
        background-color: #008457;
        border-radius: 8px;
        border: 1px solid transparent;
        padding: 0.6em 1.2em;
        font-size: 0.8em;
        font-weight: 500;
        font-family: inherit;
        color: white;
        cursor: pointer;
        height: 50px;
        transition: border-color 0.25s;
    }
    #submit:focus, #submit:focus-visible {
        outline: 4px auto -webkit-focus-ring-color;
    }
    .login-div form>a {
        font-size: 0.9rem;
        color: #B35042;
        margin-top: 2vh;
    }
    .create-link {
        font-size: 0.85rem;
    }
    .create-link a {
        margin-left: 5px;
        font-size: 0.9rem;
        color: #0078D4;
    }
    .login-div form>label {
        display: grid;
        gap: 8px;
        font-size: 0.9rem;
        color: #344556;
    }
    .login-div label>input {
        font-size: 1rem;
    }
    .name {
        display: flex;
        place-items: center;
        gap: 15px;
        font-size: 1.8rem;
        font-weight: bold;
        place-self: center;
        color: #FFF3E1;
    }
    .image-svg {
        display: block;
        text-align: center;
    }
    .image-svg img {
        width: 80%;
        animation: image-appear2 1.3s ease;
    }
    .design {
        position: absolute;
        top: 0;
        left: 0;
        width: 50vw;
        background-color: #008457;
        z-index: -100;
        height: 100vh;
    }
    .flash-messages{
        position: fixed;
        top: 10px;
        left: 50%;
        transform: translateX(-50%);
        color: white;
        background-color: red;
        border-radius: 7px;
        font-size: 1.1rem;
        padding: 10px 20px;
        font-family: monospace;
        animation: appear 0.5s ease;
    }
    @media screen and (max-width:700px) {
        .name {
            font-size: 1.6rem;
        }
        .name svg {
            width: 40px;
            height: 40px;
        }
        .login-div main>p {
            font-size: 1.2rem;
        }
    }
    @keyframes framer-appear {
        from {
            opacity: 0.6;
            transform: translate(3px, 20px);
        }
    }
    @keyframes image-appear2 {
        0% {
            opacity: 0;
        }
        20% {
            opacity: 0;
            transform: translate(3px, 20px);
        }
    }
    @keyframes appear {
        from{
            opacity: 0.6;
            top: -100%;
        }
    }
</style>
<body>
    {% with messages = get_flashed_messages(with_categories=True) %}
                    {% if messages %}
                        <div class="flash-messages">
                            {% for category, message in messages %}
                                <div class="flash-message {{ category }}">
                                    {{ message }}
                                </div>
                            {% endfor %}
                        </div>
                    {% endif %}
                {% endwith %}
    <div class="design"></div>
    <section class="login-section">
        <div class="login-div">
            <div>
                <p>Sign In with your Account</p>

                <!-- Flash messages -->
                

                <form method="POST" action="">
                    {{ form.hidden_tag() }}
                    <label>Username {{ form.username }}</label>
                    {% if form.username.errors %}
                    <ul>
                        {% for error in form.username.errors %}
                        <li>{{ error }}</li>
                        {% endfor %}
                    </ul>
                    {% endif %}
                    <label>Password {{ form.password }}</label>
                    {% if form.password.errors %}
                    <ul>
                        {% for error in form.password.errors %}
                        <li>{{ error }}</li>
                        {% endfor %}
                    </ul>
                    {% endif %}
                    
                    {{ form.submit }}
                </form>
                <div class="create-link">
                    I do not have an account? <a href="{{ url_for('main.register') }}">Create new</a>
                </div>
            </div>
        </div>
        <div class="image-svg">
            <img src="{{ url_for('static', filename='rice field-pana.svg') }}" alt="">
        </div>
    </section>
</body>
</html>

instance/templates/register.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <title>Register</title>
    <meta name="description" content="" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}" />
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Raleway:ital,wght@0,100..900;1,100..900&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Karla:ital,wght@0,200..800;1,200..800&family=Manrope:wght@200..800&family=Poppins:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900&display=swap" rel="stylesheet">
  </head>
  <style>
    body{
      height: 100vh;
      margin: 0;
      height: 100%;
      width: 100vw;
      overflow-x: hidden;
      font-size: 1.5em;
      background-color: whitesmoke;
      font-family: "Raleway",sans-serif;
    }
    .login-section{
      display: flex;
      place-items: center;
      height: 100vh;
    }
    .login-section>:first-child{
      width: 40%;
    }
    .login-section>:last-child{
      flex: 1;
    }
    
    button:hover {
      border-color: #646cff;
    }
    a{
      font-weight: 500;
      text-decoration: inherit;
    }
    .login-div{
      display: grid;
      justify-content: center;
    }
    .login-div>div{
      padding: 40px 35px;
      display: grid;
      gap: 35px;
      border-radius: 8px;
      background-color: whitesmoke;
      animation: framer-appear 1s ease-in-out;
    }
    .login-div form{
      display: grid;
      gap: 10px;
    }
    .login-div div>p{
      font-size: 1.35rem;
      font-weight: bold;
      text-align: center;
      margin: 0 0 20px 0;
      color: #151C24;
      font-family: "Manrope", sans-serif;
    }
    input {
        border: 2px solid #DEE2E5;
        background-color: transparent;
        font-family: inherit;
        height: 40px;
        outline: none;
        border-radius: 7px;
        padding-left: 10px;
        padding-right: 10px;
        caret-color: forestgreen;
    }
    input:focus{
      border-color: #B35042;
    }
    .login-div #submit {
        width: 350px;
        background-color: #008457;
        border-radius: 8px;
        border: 1px solid transparent;
        padding: 0.6em 1.2em;
        font-size: 0.8em;
        font-weight: 500;
        font-family: inherit;
        color: white;
        cursor: pointer;
        height: 50px;
        transition: border-color 0.25s;
    }
    #submit:focus, #submit:focus-visible {
        outline: 4px auto -webkit-focus-ring-color;
    }
    .login-div form>a{
      font-size: 0.9rem;
      color: #B35042;
      margin-top: 2vh;
    }
    .create-link{
      font-size: 0.85rem;
    }
    .create-link a{
      margin-left: 5px;
      font-size: 0.9rem;
      color: #0078D4;
    }
    .login-div form>label{
      display: grid;
      gap: 8px;
      font-size: 0.9rem;
      color: #344556;
    }
    .login-div label>input{
      font-size: 1rem;
    }
    .name{
      display: flex;
      place-items: center;
      gap: 15px;
      font-size: 1.8rem;
      font-weight: bold;
      place-self: center;
      color: #FFF3E1;
    }
    .image-svg{
      display: block;
      text-align: center;
    }
    .image-svg img{
      width: 80%;
      animation: image-appear2 1.3s ease;
    }
    .design{
      position: absolute;
      top: 0;
      right: 0;
      width: 60vw;
      background-color: #008457;
      z-index: -100;
      height: 100vh;
    }
    .flash-messages{
      position: fixed;
      top: 10px;
      left: 50%;
      transform: translateX(-50%);
      color: white;
      background-color: red;
      border-radius: 7px;
      font-size: 1.1rem;
      padding: 10px 20px;
      font-family: monospace;
      animation: appear 0.5s ease;
      z-index: 1000;
    }

    @media screen and (max-width:700px) {
      .name{
        font-size: 1.6rem;
      }
      .name svg{
        width: 40px;
        height: 40px;
      }
      .login-div main>p{
        font-size: 1.2rem;
      }
    }
    @keyframes framer-appear {
        from{
            opacity: 0.6;
            transform: translate(3px,20px);
        }
    }
    @keyframes image-appear2 {
      0%{
        opacity: 0;
      }
      20%{
        opacity: 0;
        transform: translate(3px,20px);
      }
    }
    @keyframes appear {
        from{
            opacity: 0.6;
            top: -100%;
        }
    }
  </style>
  <body>
    {% if form.first_name.errors %}
    <div class="flash-messages">
            {% for error in form.first_name.errors %}
            <div>{{ error }}</div>
            {% endfor %}
    </div>
    {% elif form.last_name.errors %}
    <div class="flash-messages">
      {% for error in form.last_name.errors %}
        <div>{{ error }}</div>
        {% endfor %}
    </div>
    {% elif form.username.errors %}
    <div class="flash-messages">
      {% for error in form.username.errors %}
        <div>{{ error }}</div>
        {% endfor %}
    </div>
              {% elif form.email.errors %}
              <div class="flash-messages">
                {% for error in form.email.errors %}
                  <div>{{ error }}</div>
                  {% endfor %}
              </div>
                        {% elif form.password.errors %}
                        <div class="flash-messages">
                          {% for error in form.password.errors %}
                            <div>{{ error }}</div>
                            {% endfor %}
                        </div>
                                  {% elif form.confirm_password.errors %}
                                  <div class="flash-messages">
                                    {% for error in form.confirm_password.errors %}
                                      <div>{{ error }}</div>
                                      {% endfor %}
                                  </div>
                                            {% endif %}
    <div class="design"></div>
    <section class="login-section">
      <div class="image-svg">
        <img src="../static/signup.svg" alt="Sign Up">
      </div>
      <div class="login-div">
        <div>
          <p>Register with Us</p>
          <form method="POST">
            {{ form.hidden_tag() }}
            <label>First Name
              {{ form.first_name }}
            </label>
            <label>Last Name
              {{ form.last_name }}
            </label>
            <label>Username
              {{ form.username }}
            </label>
            <label>Email
              {{ form.email }}
            </label>
            <label>Password
              {{ form.password }}
              
            </label>
            <label>Re-type Password
              {{ form.confirm_password }}
            </label>
            {{ form.submit }}
          </form>
          <div class="create-link">
            Already have an account? <a href="{{ url_for('main.login') }}">Sign In</a>
          </div>
        </div>
      </div>
    </section>
  </body>
</html>